import { checkPackagePolicy } from '../../../src/conventions/package-metadata/policy.mjs';
test('validates package policy independently', () => { expect(checkPackagePolicy({ name: 'demo' })).toEqual(expect.arrayContaining([expect.objectContaining({ message: expect.stringContaining('version') })])); });
test('checks the lint flag after the shared launcher is present', () => { expect(checkPackagePolicy({ name: 'demo', scripts: { test: 'eliware-test', lint: 'eliware-test' } }).map(({ message }) => message)).toContain('package.json: scripts.lint must invoke eliware-test --lint'); });
test('checks lint commands that contain the launcher without the flag', () => { expect(checkPackagePolicy({ name: 'demo', scripts: { test: 'eliware-test', lint: 'eliware-test extra' } }).map(({ message }) => message)).toContain('package.json: scripts.lint must invoke eliware-test --lint'); });
test('requires canonical branding metadata for public Eliware packages', () => {
  const valid = { name: '@eliware/demo', version: '1.0.0', description: 'demo', keywords: ['demo'], author: 'Eliware', license: 'MIT', repository: 'https://github.com/eliware/demo', homepage: 'https://github.com/eliware/demo#readme', scripts: { test: 'eliware-test', lint: 'eliware-test --lint' }, files: ['README.md', 'LICENSE', 'RELEASE_NOTES.md'], publishConfig: { access: 'public' } };
  expect(checkPackagePolicy(valid).map(({ message }) => message)).not.toEqual(expect.arrayContaining([expect.stringContaining('canonical repository'), expect.stringContaining('author')]));
  const messages = checkPackagePolicy({ ...valid, author: 'Someone Else', repository: 'https://github.com/example/demo' }).map(({ message }) => message);
  expect(messages).toEqual(expect.arrayContaining(['package.json: public @eliware packages must identify Eliware as the author', 'package.json: public @eliware packages must use canonical repository https://github.com/eliware/demo']));
  expect(checkPackagePolicy({ ...valid, repository: { url: 'https://github.com/eliware/demo.git' } }).map(({ message }) => message)).not.toEqual(expect.arrayContaining([expect.stringContaining('canonical repository')]));
  expect(checkPackagePolicy({ ...valid, author: undefined, repository: undefined }).map(({ message }) => message)).toEqual(expect.arrayContaining([expect.stringContaining('must identify Eliware'), expect.stringContaining('canonical repository')]));
});
